### PR TITLE
Add FreeBSD platform support

### PR DESCRIPTION
**Pull request by nxjosephofficial**
Hi. Nice tool you've made! :star: :100: 

I do want to package `gowall` for FreeBSD platform that I am daily driving. I did sent a [port request](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=282799) to FreeBSD bugzilla and waiting for it to get accepted into FreeBSD repositories and ports tree soon.

I made two patches locally that adds FreeBSD platform support by editing those two files: `utils/url.go` and `internal/image/image.go`. After added FreeBSD support, `gowall` seems to work on FreeBSD.

I made these changes in my fork and created this PR. Also attached it as a `txt` file.
 
[patch.txt](https://github.com/user-attachments/files/17787316/patch.txt)

in case of "linux", it seems to use `xdg-open` and that's already available on FreeBSD. I added a "freebsd" case with same command.

Thanks in advance.

### CODE REVIEW

**Comment by Achno** [comment]
Hello there @nxjosephofficial  thank you for the kind words,

If you want to be a maintainer and package gowall for FreeBSD like others are for NixOS and Void ( i package for the AUR) , be my guest, it would be lovely :) 

As for the patch i will merge it tommorow after i spin up FreeBSD for the first time in my life and test that it works, since im not near my computer right now and it would be pretty late when i come back.

**Comment by nxjosephofficial** [comment]
> Hello there @nxjosephofficial thank you for the kind words,

You are welcome.

> If you want to be a maintainer and package gowall for FreeBSD like others are for NixOS and Void ( i package for the AUR) , be my guest, it would be lovely :)

Thank you, I already did package `gowall` for FreeBSD but it is not in official freebsd ports tree (package tree) and repositories yet.

> As for the patch i will merge it tommorow after i spin up FreeBSD for the first time in my life and test that it works, since im not near my computer right now and it would be pretty late when i come back.

Okay, I will publish the package into [my unofficial FreeBSD ports overlay](https://github.com/nxjosephofficial/yusuf-ports-overlay) now, you can use it after you install FreeBSD to install the `gowall` on FreeBSD or you can clone the git repo and apply my patches then test. I assume you are going to install freebsd into a virtual machine.

**Comment by Achno** [comment]
Tested and works fine, merging.

**Comment by nxjosephofficial** [comment]
Nice, thanks. In readme, there are commands to install `gowall` for some distros and I can make a PR when `gowall` is passed into FreeBSD repositories, both quarterly (lts packages branch) and latest (rolling packages branch)

**Comment by Achno** [comment]
There is no need to waste time with PR's for the README right now. Since i made the docs page, i will clean up the readme and change it a lot in the coming days.

 After im done with that, you can make the PR for it for the README and i will add it to the docs page as well :)

**Pull request merged**
