### PR TITLE
Added some more themes

### PR DESCRIPTION
**Pull request by elbachir-one**

### CODE REVIEW

**Comment by Achno** [comment]
Looks good to me at a first glance. I will test everything tomorrow and merge it since it is very late at night right now.

**Comment by Achno** [comment]
Hello again just woke up,

I also saw that you added a way for void users to install gowall , pretty cool :)
have you tested it to make sure it works? I really have no idea how void does their stuff
( spin up a quick vm and check on a fresh install if you haven't please )

I also saw you fixed the internal links , im guessing now it takes you to correct section, good job.

One change i would want is to please add a `Community themes` section under the `Theme` section so the users dont get overwhelmed by the amount of themes  

ex.

- **Tokyo-moon**
- **Onedark**

#### Community Themes (emoji to convey something along the lines of a theme)
- **Monokai**
- **Material**
- **Atom One Light**
- **Sweet**
- **Synthwave 84**
- **Atom Dark**
- **Oceanic Next**
- **Shades of Purple**
- **Arc Dark**
- **Sunset Aurant**
- **Sunset Saffron**
- **Sunset Tangerine**

**Comment by Achno** [comment]
Just finished testing your PR 

Everything is fine except for the `sweet` theme which produces really bad images so i would like to remove it. ( You can see the 3 examples below )

Example 1: https://freeimage.host/i/dTILp0G
Example 2: https://freeimage.host/i/dTIQvkl
Example 3: https://freeimage.host/i/dTIZHEg

I plan to merge a PR soon which will allow anyone to just pass a config of a theme so future users can just use whatever theme they like.

As soon as you remove the `sweet` theme and give me the okay that the void installation of gowall works i will merge this 

- Thank you for contributing :0 !

**Comment by elbachir-one** [comment]
> Hello again just woke up,
> 
> I also saw that you added a way for void users to install gowall , pretty cool :) good job have you tested it to make sure it works? I really have no idea how void does their stuff ( spin up a quick vm and check on a fresh install if you haven't please , unless you installed gowall on your void install this way)
> 
> One change i would want is to please add a `Community themes` section under the `Theme` section so the users dont get overwhelmed by the amount of themes
> 
> ex.
> 
> * **Tokyo-moon**
> * **Onedark**
> 
> #### Community Themes (emoji to convey something along the lines of a theme)
> * **Monokai**
> * **Material**
> * **Atom One Light**
> * **Sweet**
> * **Synthwave 84**
> * **Atom Dark**
> * **Oceanic Next**
> * **Shades of Purple**
> * **Arc Dark**
> * **Sunset Aurant**
> * **Sunset Saffron**
> * **Sunset Tangerine**

Did the testing everything works fine.

**Comment by elbachir-one** [comment]
Mad a new PR.

**Pull request closed without merging**
